<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0ea3cf0cf8ab0e9f65b7ad3f1d44518d
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0ea3cf0cf8ab0e9f65b7ad3f1d44518d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0ea3cf0cf8ab0e9f65b7ad3f1d44518d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
